# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'


- script: |
    git config --global url."https://${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}@bitbucket.org/".insteadOf "https://bitbucket.org/"
  displayName: 'Inject Bitbucket Credentials into Git Config'
  env:
    BITBUCKET_USERNAME: $(BITBUCKET_USERNAME)
    BITBUCKET_APP_PASSWORD: $(BITBUCKET_APP_PASSWORD)

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Prod(202d4be6-e0dd-4b9e-84b7-e235d53271a8)'
    backendAzureRmResourceGroupName: 'NEWRG'
    backendAzureRmStorageAccountName: 'azurekssvc'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'validate'