terraform {
  backend "azurerm" {
    resource_group_name  = "NEWRG"
    storage_account_name = "azurekssvc21"
    container_name       = "terraformstate"
    key                  = "terraform.tfstate"
  }
}

